#### K8s configuration ####
## Number of replicas to create (only 1 is supported)
replicaCount: 1

image:
  repository: "factoriotools/factorio"
  ## Container image pull policy
  pullPolicy: Always
  ## Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  ## You should set an fix version, i.e.:
  # tag: "1.1.37"

nodeSelector: {}
#  beta.kubernetes.io/os: linux
#  beta.kubernetes.io/arch: amd64
#  kubernetes.io/hostname: your-cool-hostname


## The service is a kind tricky, so factorio uses UDP, but not every cloud provider is able to route UDP traffic.
## I.e. your cloud provider has LoadBalancers without the ability for UDP protocol. Furthermore kubectl ist not able to route UDP Traffic
## ref: https://github.com/kubernetes/kubernetes/issues/47862
## You have to expose factorio on a NodePort and map a port between 30000 and 32767, but the native port is 34197. So you have always to specify the port in factorio.
## The best way ist to define a ClusterIP service and define one or more externalIPs. Of course this IPs must be avaiable on the node the factorio pod runs on !
service:
  type: NodePort
  port: 31497
  ## If you are able to map an external IP, set it here
  # externalIPs:
  #  - "192.168.0.1"
  #  - "192.168.0.2"
  #
  #
  ## If you use "type: NodePort" set the port to a value you like in the range of 30000-32767. Leave it blank for a random port
  # nodePort: ""
  ## Examples:
  ## NodePort setup

  ## ClusterIp setup
  # ClusterIP:
  #   port: 34197
  ## LoadBalancer setup
  # type: LoadBalancer
  annotations: {}


## Compute Resources required by the operator container
resources:
  ## We have to ensure that factorio have enough computing resources avaiable. We set here an absolute minimum
  ## Keep in mind that big factorio base can consume a lot of memory and cpu
  requests:
    memory: 512Mi
    cpu: 500m
  ## If you like to limit factiorio resources
  # limits:
  #   memory: 1024Mi
  #   cpu: 1000m


## Strategy used to replace old pods
## IMPORTANT: use with care, it is suggested to leave as that for upgrade purposes
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
strategy:
  type: Recreate
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0

# Tolerations for pod assignment
tolerations: []

# Affinity rules for pod assignment
affinity: {}

## Sets the data persistence volume configuration
## IMPORTANT: If you do not setup a PV all your savegames will be lost on pod recreation or helm upgrade
persistence:
  enabled: true
  dataDir:
    Size: "1Gi"
    ## If you have an existing claim, set your name here
    # existingClaim: "existing-claim-name"
  ## If you like to use a specific storageClassName, set the name. Leave it blank for the default class
  storageClassName: ""
  ## If you have annotations to spin up a PV i.e. the location. Remove the curly braces
  annotations: {}


#### factorio application configuration ####
mods:
  enabled: false
# in order to use the mods portal you will need to specify the username and token in the server_settings.
  portal: []
#     - Krastorio2
#     - StorageTank2_Updated
#     - early-robots
# unofficial section is meant to just allow you to download and place folders into the mods folder.
# we will not check version compatibility automatically with these downloads.
# you can encounter an error if the file names dont match what the mod is expecting for example
# Error Util.cpp:83: Failed to load mod "Squeak-Through": Filename of mod
# /factorio/mods/Squeak-Through.zip doesn't match the expected Squeak Through_1.8.2.zip (case sensitive!)
  unofficial: []
#     - url: "https://github.com/Suprcheese/Squeak-Through/archive/refs/tags/1.8.2.zip"
#       name: "Squeak Through_1.8.2.zip"

factorioServer:
  # specify a save name
  save_name: "replaceMe"
  # Generate a New Save
  generate_new_save: true
  # Update mods on start
  update_mods_on_start: false
  # lets the game know if you want to load the latest save
  load_latest_save: true

account:
  # Existing secret containing a valid factorio.com username and either a password or a token
  # Example:
  #
  # apiVersion: v1
  # kind: Secret
  # metadata:
  #   name: account-secret
  # data:
  #   username: <username in base64>
  #   password: <password in base64>
  #
  # accountSecret: account-secret
  accountSecret: ''
  # Your factorio.com login credentials. Required for games with visibility public
  username: ''
  password: ''
  # Authentication token. May be used instead of password above.
  token: ''

serverPassword:
  # password required to log into the factorio server
  game_password: ''
  # Existing Secret containing a `game_password` data entry
  passwordSecret: ''

server_settings:
  # Your Instance Name
  name: Factorio
  # Your Instance Description
  description: "Factorio running on Kubernetes"
  tags:
  - game
  - tags
  # Maximum number of players allowed, admins can join even a full server. 0 means unlimited.
  max_players: 0
  # Game visibility
  visibility:
    # Game will be published on the official Factorio matching server
    public: false
    # Game will be broadcast on LAN
    lan: true

  # When set to true, the server will only allow clients that have a valid Factorio.com account
  require_user_verification: false
  # optional, default value is 0. 0 means unlimited.
  max_upload_in_kilobytes_per_second: 0
  # optional, default value is 5. 0 means unlimited.
  max_upload_slots: 5
  # optional one tick is 16ms in default speed, default value is 0. 0 means no minimum.
  minimum_latency_in_ticks: 0
  # Players that played on this map already can join even when the max player limit was reached.
  ignore_player_limit_for_returning_players: false
  # possible values are, true, false and admins-only
  allow_commands: admins-only
  # Autosave interval in minutes
  autosave_interval: 10
  # server autosave slots, it is cycled through when the server autosaves.
  autosave_slots: 5
  # How many minutes until someone is kicked when doing nothing, 0 for never.
  afk_autokick_interval: 0
  # Whether should the server be paused when no players are present.
  auto_pause: true
  # specifies if anyone can pause or only admins
  only_admins_can_pause_the_game: true
  # Whether autosaves should be saved only on server or also on all connected clients. Default is true.
  autosave_only_on_server: true
  #  Highly experimental feature, enable only at your own
  #  risk of losing your saves. On UNIX systems, server will fork itself to create an
  #  autosave. Autosaving on connected Windows clients will be disabled regardless of
  #  autosave_only_on_server option.
  non_blocking_saving: false
  #  Long network messages are split into segments that are sent
  #  over multiple ticks. Their size depends on the number of peers currently connected.
  #  Increasing the segment size will increase upload bandwidth requirement for the server
  #  and download bandwidth requirement for clients. This setting only affects server
  #  outbound messages. Changing these settings can have a negative impact on connection
  #  stability for some clients.
  minimum_segment_size: 25
  minimum_segment_size_peer_count: 20
  maximum_segment_size: 100
  maximum_segment_size_peer_count: 10

# Password and port for the rcon service
rcon:
  external: true
  type: LoadBalancer

  # Existing secret containing a `password` data field
  passwordSecret: ""

  # Password for rcon
  password: null

  # rcon port
  port: 30100

map_gen_settings:
  # The inverse of water scale in the map generator GUI.
  terrain_segmentation: 1
  #  The equivalent to water coverage in the map generator GUI. Higher coverage means
  #  more water in larger oceans.
  #  Water level = 10 * log2(this value)
  water: 1
  # Width and height of map, in tiles; 0 means infinite
  width: 0
  # Width and height of map, in tiles; 0 means infinite
  height: 0
  # Multiplier for biter free zone radius
  starting_area: 1
  peaceful_mode: false
  autoplace_controls:
    coal:
      frequency: 1
      size: 1
      richness: 1
    stone:
      frequency: 1
      size: 1
      richness: 1
    copper-ore:
      frequency: 1
      size: 1
      richness: 1
    iron-ore:
      frequency: 1
      size: 1
      richness: 1
    uranium-ore:
      frequency: 1
      size: 1
      richness: 1
    crude-oil:
      frequency: 1
      size: 1
      richness: 1
    trees:
      frequency: 1
      size: 1
      richness: 1
    enemy-base:
      frequency: 1
      size: 1
      richness: 1
  cliff_settings:
    # Name of the cliff prototype
    name: cliff
    # Elevation of first row of cliffs
    cliff_elevation_0: 10
    # Elevation difference between successive rows of cliffs.
    # This is inversely proportional to frequency in the map generation GUI. Specifically, when set from the GUI the value is 40 / frequency.
    cliff_elevation_interval: 40
    # Called cliff continuity in the map generator GUI. 0 will result in no cliffs, 10 will make all cliff rows completely solid
    richness: 1
  # Overrides for property value generators (map type)
  # Leave elevation blank to get normal terrain.
  # Use ''elevation'': ''0_16-elevation'' to reproduce terrain from 0.16.
  # Use ''elevation'': ''0_17-island'' to get an island.
  # Moisture and terrain type are also controlled via this.
  # "control-setting:moisture:frequency:multiplier is the inverse of the moisture scale in the map generator GUI."
  # "control-setting:moisture:bias is the moisture bias in the map generator GUI."
  # "control-setting:aux:frequency:multiplier is the inverse of the terrain type scale in the map generator GUI."
  # "control-setting:aux:bias is the teraain type bias in the map generator GUI."
  property_expression_names:
    control-setting:moisture:frequency:multiplier: '1'
    control-setting:moisture:bias: '0'
    control-setting:aux:frequency:multiplier: '1'
    control-setting:aux:bias: '0'
  starting_points:
  - "x": 0
    "y": 0
  # Use null for a random seed, number for a specific seed.
  seed: null

map_settings:
  difficulty_settings:
    recipe_difficulty: 0
    technology_difficulty: 0
    technology_price_multiplier: 1
    research_queue_setting: after-victory
  pollution:
    enabled: true
    # these are values for 60 ticks (1 simulated second)
    # amount that is diffused to neighboring chunk
    diffusion_ratio: 0.02
    min_to_diffuse: 15
    ageing: 1
    expected_max_per_chunk: 150
    min_to_show_per_chunk: 50
    min_pollution_to_damage_trees: 60
    pollution_with_max_forest_damage: 150
    pollution_per_tree_damage: 50
    pollution_restored_per_tree_damage: 10
    max_pollution_to_restore_trees: 20
    enemy_attack_pollution_consumption_modifier: 1
  enemy_evolution:
    enabled: true
    time_factor: 0.000004
    destroy_factor: 0.002
    pollution_factor: 0.0000009
  enemy_expansion:
    enabled: true
    min_base_spacing: 3
    max_expansion_distance: 7
    friendly_base_influence_radius: 2
    enemy_building_influence_radius: 2
    building_coefficient: 0.1
    other_base_coefficient: 2
    neighbouring_chunk_coefficient: 0.5
    neighbouring_base_chunk_coefficient: 0.4
    max_colliding_tiles_coefficient: 0.9
    settler_group_min_size: 5
    settler_group_max_size: 20
    min_expansion_cooldown: 14400
    max_expansion_cooldown: 216000
  unit_group:
    min_group_gathering_time: 3600
    max_group_gathering_time: 36000
    max_wait_time_for_late_members: 7200
    max_group_radius: 30
    min_group_radius: 5
    max_member_speedup_when_behind: 1.4
    max_member_slowdown_when_ahead: 0.6
    max_group_slowdown_factor: 0.3
    max_group_member_fallback_factor: 3
    member_disown_distance: 10
    tick_tolerance_when_member_arrives: 60
    max_gathering_unit_groups: 30
    max_unit_group_size: 200
  steering:
    default:
      radius: 1.2
      separation_force: 0.005
      separation_factor: 1.2
      force_unit_fuzzy_goto_behavior: false
    moving:
      radius: 3
      separation_force: 0.01
      separation_factor: 3
      force_unit_fuzzy_goto_behavior: false
  path_finder:
    fwd2bwd_ratio: 5
    goal_pressure_ratio: 2
    max_steps_worked_per_tick: 100
    max_work_done_per_tick: 8000
    use_path_cache: true
    short_cache_size: 5
    long_cache_size: 25
    short_cache_min_cacheable_distance: 10
    short_cache_min_algo_steps_to_cache: 50
    long_cache_min_cacheable_distance: 30
    cache_max_connect_to_cache_steps_multiplier: 100
    cache_accept_path_start_distance_ratio: 0.2
    cache_accept_path_end_distance_ratio: 0.15
    negative_cache_accept_path_start_distance_ratio: 0.3
    negative_cache_accept_path_end_distance_ratio: 0.3
    cache_path_start_distance_rating_multiplier: 10
    cache_path_end_distance_rating_multiplier: 20
    stale_enemy_with_same_destination_collision_penalty: 30
    ignore_moving_enemy_collision_distance: 5
    enemy_with_different_destination_collision_penalty: 30
    general_entity_collision_penalty: 10
    general_entity_subsequent_collision_penalty: 3
    extended_collision_penalty: 3
    max_clients_to_accept_any_new_request: 10
    max_clients_to_accept_short_new_request: 100
    direct_distance_to_consider_short_request: 100
    short_request_max_steps: 1000
    short_request_ratio: 0.5
    min_steps_to_check_path_find_termination: 2000
    start_to_goal_cost_multiplier_to_terminate_path_find: 500
    overload_levels:
    - 0
    - 100
    - 500
    overload_multipliers:
    - 2
    - 3
    - 4
    negative_path_cache_delay_interval: 20
  max_failed_behavior_count: 3

admin_list:
  # - "john_doe"
  # - "jane_doe"

white_list:
  # - "john_doe"
  # - "jane_doe"

ban_list:
  # - "john_doe"
  # - "jane_doe"
